# =============================================================================
# BASE CONFIGURATION
# =============================================================================

ARG PYTHON_VERSION=3.7.6-alpine3.10

# =============================================================================
# BASE ENV
# =============================================================================

FROM python:${PYTHON_VERSION}

LABEL maintainer="Lucca Pessoa da Silva Matos - luccapsm@gmail.com"

WORKDIR /usr/src/app/

COPY [ "./code", "." ]

ENTRYPOINT []

CMD [ "sh" ]
